"""Models for the use with LibForeman"""
from __future__ import division
from __future__ import print_function
from __future__ import with_statement

from collections import namedtuple

# Datastructure for results generated by the workers
Task = namedtuple("Task", ["args"])

# Datastructure for results generated by the workers
Result = namedtuple("Result", ["id", "performance"])

# data structure for a worker process and attached queues
Worker = namedtuple("Worker", \
                    ["id", "process", "queue_tasks", "queue_results"])

# data struture for a pool of workers
Pool = namedtuple("Pool", ["workers", "queue_results"])
